#define NUM_SENSOR_READINGS_TO_STORE 10

const float TEMP_HIGH_HIGH = 93.0;
const float TEMP_HIGH_LOW = 90.0;
const float TEMP_LOW_HIGH = 50.0;
const float TEMP_LOW_LOW = 50.0;

const float HUMIDITY_HIGH_HIGH = 63.0;
const float HUMIDITY_HIGH_LOW = 60.0;
const float HUMIDITY_LOW_HIGH = 33.0;
const float HUMIDITY_LOW_LOW = 30.0;

const float PRESSURE_HIGH_HIGH = 1000.0;
const float PRESSURE_HIGH_LOW = 995.0;
const float PRESSURE_LOW_HIGH = 905.0;
const float PRESSURE_LOW_LOW = 900.0;


float TEMP_LAST_X_READINGS[NUM_SENSOR_READINGS_TO_STORE];
float HUMIDITY_LAST_X_READINGS[NUM_SENSOR_READINGS_TO_STORE];
float PRESSURE_LAST_X_READINGS[NUM_SENSOR_READINGS_TO_STORE];
float ILLUMINANCE_LAST_X_READINGS[NUM_SENSOR_READINGS_TO_STORE];